/**
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RatesBookPostRequestGuestInfo } from './ratesBookPostRequestGuestInfo';
import { RatesBookPostRequestPayment } from './ratesBookPostRequestPayment';

export class RatesBookPostRequest {
    /**
    * prebook id retrived from prebook response
    */
    'prebookId': string;
    'guestInfo': RatesBookPostRequestGuestInfo;
    'payment'?: RatesBookPostRequestPayment;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prebookId",
            "baseName": "prebookId",
            "type": "string"
        },
        {
            "name": "guestInfo",
            "baseName": "guestInfo",
            "type": "RatesBookPostRequestGuestInfo"
        },
        {
            "name": "payment",
            "baseName": "payment",
            "type": "RatesBookPostRequestPayment"
        }    ];

    static getAttributeTypeMap() {
        return RatesBookPostRequest.attributeTypeMap;
    }
}

