/**
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RatesBookPostRequestPayment {
    'holderName': string;
    'number'?: string;
    'expireDate'?: string;
    'cvc'?: string;
    'method': RatesBookPostRequestPayment.MethodEnum;
    'token'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "holderName",
            "baseName": "holderName",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string"
        },
        {
            "name": "expireDate",
            "baseName": "expireDate",
            "type": "string"
        },
        {
            "name": "cvc",
            "baseName": "cvc",
            "type": "string"
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "RatesBookPostRequestPayment.MethodEnum"
        },
        {
            "name": "token",
            "baseName": "token",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RatesBookPostRequestPayment.attributeTypeMap;
    }
}

export namespace RatesBookPostRequestPayment {
    export enum MethodEnum {
        CreditCard = <any> 'CREDIT_CARD',
        StripeToken = <any> 'STRIPE_TOKEN'
    }
}
