/**
 * Lite API
 * The **Lite API** can be used to to do the following  Get room rates & availability for a set of hotels Select a specific hotel with room availability and make a booking Manage the bookings - retrieve and cancel existing bookings Get static content for hotels, search hotels by destination
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RatesBookPostRequestGuestInfo {
    /**
    * traveler first name
    */
    'guestFirstName': string;
    /**
    * traveler last name
    */
    'guestLastName': string;
    /**
    * traveler email
    */
    'guestEmail': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "guestFirstName",
            "baseName": "guestFirstName",
            "type": "string"
        },
        {
            "name": "guestLastName",
            "baseName": "guestLastName",
            "type": "string"
        },
        {
            "name": "guestEmail",
            "baseName": "guestEmail",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return RatesBookPostRequestGuestInfo.attributeTypeMap;
    }
}

